kubernetesClusterDomain: cluster.local

# -- Replica count for the service, default is 1
replicaCount: 1


skaha:
  # -- The namespace for the service, **Note:** This namespace is common between the Skaha and POSIX Mapper services. Do not change.
  namespace: skaha-system

# POSIX Mapper web service deployment
deployment:
  # -- Hostname for the service, **Note:** Change this to your domain.
  hostname: example.host.com
  posixMapper:
    # -- The image for the service
    image: images.opencadc.org/platform/posix-mapper:0.2.1
    # -- The image pull policy for the service
    imagePullPolicy: Always
    # -- IVOA Resource ID for the service
    resourceID: ivo://example.org/posix-mapper

    # -- URI or URL of the OIDC (IAM) server.  Used to validate incoming tokens.
    oidcURI: iam.example.org

    # -- ID (URI) of the GMS Service.
    gmsID: ivo://example.org/gms

    # Optionally set the DEBUG port.
    # extraEnv:
    # - name: CATALINA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"
    # - name: JAVA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"

    # Uncomment to debug.  Requires options above as well as service port exposure below.
    # extraPorts:
    # - containerPort: 5555
    #   protocol: TCP

    # -- Resources provided to the Skaha service.
    resources:
      requests:
        # -- Memory Requested
        memory: "1Gi"
        # -- CPU Requested
        cpu: "500m"
      limits:
        # -- Memory Limit
        memory: "1Gi"
        # -- CPU Limit
        cpu: "500m"

    # -- Minimum UID, **should be high so as not to conflict with Image UIDs**.
    minUID: 10000
    # -- Minimum GID, **should be high so as not to conflict with Image GIDs**.
    minGID: 900000
    # -- Registry URL
    registryURL: https://example.org/reg

    # Optionally mount a custom CA certificate
    # extraVolumeMounts:
    # - mountPath: "/config/cacerts"
    #   name: cacert-volume

    # Create the CA certificate volume to be mounted in extraVolumeMounts
    # extraVolumes:
    # - name: cacert-volume
    #   secret:
    #     defaultMode: 420
    #     secretName: posix-manager-cacert-secret

  # Specify extra hostnames that will be added to the Pod's /etc/hosts file.  Note that this is in the
  # deployment object, not the posixMapper one.
  #
  # These entries get added as hostAliases entries to the Deployment.
  #
  # Example:
  # extraHosts:
  #   - ip: 127.3.34.5
  #     hostname: myhost.example.org
  #
  # extraHosts: []
secrets:
  # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
  # posix-manager-cacert-secret:
  #   ca.crt: <base64 encoded ca crt>

# These values are preset in the catalina.properties, and this default database only exists beside this service.
# It's usually safe to leave these as-is, but make sure they match the values in catalina.properties.
# -- The database connection information for the service
postgresql:
  maxActive: 8
  auth:
    username: posixmapper
    password: posixmapperpwd
    database: mapping
    schema: mapping
  storage:
    spec:
      hostPath:
        path: "/posix-mapper/data"
