apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadc-sssd-ds
  labels:
    k8s-app: cadc-sssd-ds
spec:
  selector:
    matchLabels:
      name: cadc-sssd-ds
  template:
    metadata:
      labels:
        name: cadc-sssd-ds
    spec:
      initContainers:
      - name: init-sssd-dir
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - mkdir -p /var/lib/sss/pipes/private;
          chmod 1755 /var/lib/sss/pipes/private;
        volumeMounts:
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      containers:
      - name: cadc-sssd-ds
        image: images.canfar.net/skaha-system/sssd:1.0
        imagePullPolicy: Always
        #command: ["/bin/sh"]
        #args: ["-c", "while true; do sleep 10;done"]
        volumeMounts:
        - mountPath: /etc/sssd/sssd.conf
          subPath: sssd.conf
          name: sssd-config-vol
        - mountPath: /etc/openldap/certs/ca.crt
          subPath: ca.crt
          name: sssd-cert-config-vol
        - mountPath: /etc/openldap/certs/cadc_CA_2029.crt
          subPath: cadc_CA_2029.crt
          name: sssd-cert-config-vol
        - mountPath: /var/lib/sss/pipes
          name: sssd-dir
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 0
      serviceAccountName: sss
      priorityClassName: uber-user-preempt-high
      volumes:
      - name: sssd-config-vol
        configMap:
          name: sssd-config
          # defaultMode of 256 sets the permissions of the file
          # to 0400 - needed by sssd
          defaultMode: 256
      - name: sssd-cert-config-vol
        configMap:
          name: sssd-cert-config
      - name: sssd-dir
        hostPath:
          path: /var/lib/ubernetes
          type: Directory
