# kubernetesClusterDomain: This key defines the DNS domain name used within the Kubernetes cluster.
# cluster.local: This is the default domain name for Kubernetes clusters.
# It is used for internal DNS resolution within the cluster, allowing services to communicate with each other using DNS names
# like service.namespace.svc.cluster.local.

# -- DNS domain name used within the Kubernetes cluster to allow service communication, e.g. service.namespace.svc.cluster.local
kubernetesClusterDomain: cluster.local

skaha:
  # -- The namespace for the Skaha system components
  namespace: skaha-system

skahaWorkload:
  # -- The namespace for the Skaha Workload components, e.g. User JupyterHub
  namespace: skaha-workload

developer:
  storage:
    # -- **Dev Only:** The path to local storage for skaha-system, this path needs to exist on the host.
    skahaStoragePath: null
    # -- **Dev Only:** The path to local storage for skaha-workload, this path needs to exist on the host
    skahaWorkloadStoragePath: null


secrets:
  # -- **Dev Only:** The secret for Traefik Ingress SSL Termination, dont use in production!!!
  default-certificate:
    # -- **Dev Only:** Base64 encoded server certificate
    tls.crt: null
    # -- **Dev Only:** Base64 encoded server key
    tls.key: null

# Don't install Traefik by default. Set to true to add it in.
traefik:
  # -- **Dev Only:** Whether to install Traefik (default: false)
  install: false
  logs:
    general:
      # -- **Dev Only:** The format of the logs, e.g. common, json, or logfmt
      format: common
      # -- **Dev Only:** Logging level: DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      level: ERROR
    access:
      # -- **Dev Only:** To enable access logs
      enabled: false
  # -- **Dev Only:** See dev.overrides.yaml for more options
  tlsStore: {}
  # -- **Dev Only:** See dev.overrides.yaml for more options
  tlsOptions: {}
