apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: carta-forwardauth
spec:
  forwardAuth:
    # NOTE: Update this address to match your system namespace
    # Format: http://carta-sidecar.<SYSTEM_NAMESPACE>.svc/
    address: http://carta-sidecar.skaha-system.svc/
    trustForwardHeader: true
    authRequestHeaders:
      - Authorization
      - Cookie
      - X-Forwarded-Uri
      - X-Forwarded-Method
      - X-Forwarded-Proto
      - X-Forwarded-Host
    authResponseHeaders:
      - carta-auth-token
