apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canfarops-pods-cadc-sssd-binding
  labels:
  {{- include "base.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'pods-clusterrole'
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: canfarops
  namespace: '{{ .Release.Namespace }}'
