apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configmaps-clusterrole
  labels:
  {{- include "base.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
