# Iterate over the secrets defined in the values.yaml
{{- range $secretName, $secretValues := .Values.secrets }}
  {{- $validSecret := false }}
  # For each secret, check if it has any values
  {{- range $secretKey, $secretValue := .}}
    {{- if $secretValue }}
      # If there is a value, set the validSecret flag to true
      {{- $validSecret = true }}
    {{- end }}
  {{- end }}
  # If the secret has any values, create a Secret resource
  {{- if $validSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  {{- range $secretKey, $secretValue := . }}
    {{ $secretKey }}: {{ $secretValue | quote }}
  {{- end }}
  {{- end }}
{{- end }}
