{{- range $secretName, $secretValues := .Values.secrets }}
  {{- $validSecret := false }}
  {{- range $secretKey, $secretValue := .}}
    {{- if $secretValue }}
      {{- $validSecret = true }}
    {{- end }}
  {{- end }}
  {{- if $validSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
type: Opaque
data:
  {{- range $secretKey, $secretValue := . }}
    {{ $secretKey }}: {{ $secretValue | quote }}
  {{- end }}
  {{- end }}
{{- end }}
