apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    run: {{ .Release.Name }}-service
spec:
  ports:
    - port: 80
      name: http-{{ .Release.Name }}
      protocol: TCP
  selector:
    run: {{ .Release.Name }}-service