apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.skaha.namespace }}
  annotations:
    spec.ingressClassName: traefik
spec:
  rules:
  - host: {{ .Values.deployment.hostname }}
    http:
      paths:
      - path: /reg
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 80