#-- DNS domain name used within the Kubernetes cluster to allow service communication, e.g. service.namespace.svc.cluster.local
kubernetesClusterDomain: cluster.local

#-- Number of replicas to run
replicaCount: 1


skaha:
  #-- The namespace for the Skaha system components, it recommended to leave this as is
  namespace: skaha-system

# Skaha web service deployment
deployment:
  #-- The hostname for the service
  hostname: example.org
  cavern:
    #-- The image to use for the service
    image: images.opencadc.org/platform/cavern:0.7.13
    #-- The image pull policy
    imagePullPolicy: Always

    #-- Self identifying resource ID for the service
    resourceID: "ivo://example.org/cavern"

    # Set the Registry URL pointing to the desired registry (https:// URL)
    # registryURL: https://example.org/reg

    # The Resource ID of the Service that contains the Posix Mapping information
    # posixMapperResourceID: "ivo://example.org/posix-mapper"

    # URI or URL of the OIDC (IAM) server.  Used to validate incoming tokens.  Required.
    # oidcURI: https://ska-iam.stfc.ac.uk/

    # ID (URI) of the GMS Service.  Required
    # gmsID: ivo://skao.int/gms

    # Array of groups allowed to set the logging level.  If none set, then nobody can change the log level.
    # loggingGroups: []

    # Simple Class name of the QuotaPlugin to use.  This is used to request quota and folder size information
    # from the underlying storage system.  Optional, defaults to NoQuotaPlugin.
    #
    # - For CephFS deployments: CephFSQuotaPlugin
    # - Default: NoQuotaPlugin
    #
    # quotaPlugin: {NoQuotaPlugin | CephFSQuotaPlug}

    filesystem:
      #-- Persistent data directory in container
      dataDir: "/data"

      # RELATIVE path to the node/file content that could be mounted in other containers
      # This will be used in a `dataDir`/`subPath` manner to remove shared data from the root folder.
      # subPath: "cavern"

      # The adminUsername is required to be set whomever has admin access over the
      # filesystem.dataDir above.
      rootOwner:
        #-- The admin username for the filesystem.dataDir
        adminUsername: "root"
        #-- The username for the filesystem.dataDir
        username: "root"
        #-- The user id for the filesystem.dataDir
        uid: 1000
        #-- The group id for the filesystem.dataDir
        gid: 1000

      # (optional) base directory exposed for sshfs mounts
      # sshfs:
      #   serverBase: {server}[:{port}]:{path}

    # The IdentityManager class handling authentication.  This should generally be left alone.
    identityManagerClass: org.opencadc.auth.StandardIdentityManager

    # For the UWS database.
    uws:
      db:
        username: "uwsuser"
        password: "uwspwd"
        database: "uws"  # OR url below.
        # url: "jdbc:postgresql://<host>:<port>/<database>"
        schema: "uws"
        maxActive: 2
        runUID: 999  # Postgres User default in the postgres:13 image

    # Optional rename of the application from the default "cavern".
    applicationName: "cavern"

    # The endpoint to serve this from.  Defaults to /cavern.  If the applicationName is changed, then this should match.
    # Don't forget to update your registry entries!
    endpoint: "/cavern"

    # Optionally set the DEBUG port.
    # extraEnv:
    # - name: CATALINA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"
    # - name: JAVA_OPTS
    #   value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:5555"

    # Optionally mount a custom CA certificate
    # extraVolumeMounts:
    # - mountPath: "/config/cacerts"
    #   name: cacert-volume

    # Create the CA certificate volume to be mounted in extraVolumeMounts
    # extraVolumes:
    # - name: cacert-volume
    #   secret:
    #     defaultMode: 420
    #     secretName: skaha-cacert-secret

    # Resources provided to the Skaha service.
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"

  # Specify extra hostnames that will be added to the Pod's /etc/hosts file.  Note that this is in the
  # deployment object, not the skaha one.
  # extraHosts:
  #   - ip: 127.3.34.5
  #     hostname: myhost.example.org
  # extraHosts: []

secrets:
  # Uncomment to enable local or self-signed CA certificates for your domain to be trusted.
  # cavern-cacert-secret:
  #   ca.crt: <base64 encoded CA crt>

# Exposed extra ports.  Uncomment the java-debug port to expose and debug issues.
# service:
#   cavern:
#     extraPorts:
  #   - port: 5555
  #     protocol: TCP
  #     name: java-debug

# Set these appropriately to match your Persistent Volume Claim labels.
storage:
  service:
    spec:
      # YAML for service mounted storage.
      # Example is the persistentVolumeClaim below.  Do not uncomment this
      # or Helm will use it as the default, even if a different spec
      # is specified.
      # persistentVolumeClaim:
      #   claimName: skaha-pvc
