name: Commit Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  commit-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Conventional Commitlint
      uses: opensource-nepal/commitlint@v1.3.0
  