name: Continuous Integration

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup pre-commit
      uses: pre-commit/action@v3.0.1

  unit-tests:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Say hello
      run: echo "Hello, world!"
  
